version: '3'
services:
  web1:
    build: .
    ports:
      - "8080:8080"
  web2:
    build: .
    ports:
      - "8081:8080"
  web3:
    build: .
    ports:
      - "8082:8080"
  redis:
    image: redis
    expose:
      - "6379"
    volumes:
      - ./redis-data:/data
